spring:
  kafka:
    bootstrap-servers: 192.168.1.200:9092,192.168.1.206:9092,192.168.1.207:9092
    consumer:
      group-id: eriwn-kafka-demo
      # 最早未被消费的offset
      auto-offset-reset: earliest
      # 批量一次最大拉取数据量
      max-poll-records: 1000
      # 自动提交
      auto-commit-interval: 1000
      enable-auto-commit: true


kafka:
  topic:
    default: erwin-kafka-demo
