
spring:
  kafka:
    bootstrap-servers: 192.168.1.200:9092,192.168.1.206:9092,192.168.1.207:9092
    consumer:
      group-id: erwin-kafka-demo
      # 最早未被消费的offset
      auto-offset-reset: earliest
      # 批量一次最大拉取数据量
      max-poll-records: 10000
      # 自动提交
      auto-commit-interval: 10000
      enable-auto-commit: true
    listener:
      concurrency: 10


kafka:
  topic:
    default: erwin-kafka-demo
